[package]
name = "notify-logger"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
chrono = "0.4.42"
dirs-next = "2.0.0"
regex = "1.12.2"
zbus = { version = "5", features = ["blocking"] }
